### ISSUE TITLE
No lesson name

### ISSUE THREAD

**Issue by MrTomek** [rico-et22/elektronik-timetable#23]
https://plan-lekcji.zse.rzeszow.pl/room/1

On the page with a list of lessons in a specific classroom. 

![image](https://github.com/rico-et22/elektronik-timetable/assets/13391813/e316bd20-fd69-4615-bd4d-0c52a2d2985f)

**Comment by rico-et22** [comment]
That's because the original plan also doesn't display them:
![image](https://github.com/rico-et22/elektronik-timetable/assets/28688352/e97df7c1-38c1-4053-8be2-f1372fa46a9f)
