### ISSUE TITLE
Mapping teacher room supervisor to classroom and Polish characters to without Polish symbols in search

### ISSUE THREAD

**Issue by MrTomek** [rico-et22/elektronik-timetable#6]
### Classroom:

- W.Liszcz (WL) -> 4d
- L.Świerk (LS) - > 110
- ...

 ### Without Polish symbols:
 
- Ś -> S
- Ł -> L
- ...

**Comment by rico-et22** [comment]
Polish characters resolved in #7

**Comment by MrTomek** [comment]
How are you progressing ?

**Comment by rico-et22** [comment]
@MrTomek
1. The original Vulcan timetable does not provide room supervisor data, so it's not easily possible to make such a feature. It would require a custom-made API, admin panel, and backend to manually set up such data and I don't think school admins will be eager to maintain it.
2. Polish characters already resolved in PR #7

As of now, I'm closing the issue.
